### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by klippx** [plouc/mozaik-ext-jenkins#10]
Hello!

When trying to use this plugin I get this error `[jenkins] Error: unable to verify the first certificate`. This is because of a custom CA provided to me by my company, but superagent is not used by mozaik in a way that it is configurable to pick up a specific certificate.

Since I need this certificate when I deploy my dashboard I think it would be nice to share my solution to this problem, see coming pull request.

**Comment by plouc** [comment]
fixed by https://github.com/plouc/mozaik-ext-jenkins/pull/11
