### ISSUE TITLE
status code: undefined

### ISSUE THREAD

**Issue by tomav** [plouc/mozaik-ext-jenkins#12]
I'm testing Mozaik with 2 different Jenkins, both having the rest json enabled and exposing data to my jenkins user.

I'm getting a `status code: undefined` error on one of them.
Before I dig inside, I was wondering:
- is there a particular jenkins version requirement?
- do the client works on untrusted HTTPS connection?

Thank you.

**Comment by plouc** [comment]
Didn't had the opportunity to test a lot of jenkins versions, the only thing which didn't worked with older jenkins versions was the pipeline API? which is not used for now.

Not sure for the untrusted connection, you should try to run the Mozaïk backend with this env var `NODE_TLS_REJECT_UNAUTHORIZED=0`or set a custom certificate authority thanks to the recently merged PR from @klippx https://github.com/plouc/mozaik-ext-jenkins/pull/11.

**Comment by tomav** [comment]
Worked! This could be added to documentation BTW.
Thank you @plouc
