### ISSUE TITLE
Jenkins auth and pass config

### ISSUE THREAD

**Issue by tomav** [plouc/mozaik-ext-jenkins#2]
Hi @plouc, how are you mate?

Really nice work on Mozaïk. I'm currently trying it because I need an Enterprise dashboard.
Just a question regarding the Jenkins configuration.
The `README` says:

```
{
  //… 
  api: {
    jenkins: {
      baseUrl: 'https://my-jenkins.ci',
      auth: {
        user:     'user',
        password: 'password'
      }
    }
  }
}
```

But I think it should be:

```
{
  //… 
  api: {
      jenkins: {
          baseUrl: 'https://my-jenkins.ci',
          basicAuthUser:     'user',
          basicAuthPassword: 'password'
      }
  },  
}
```

When I use your config, the server doesn't start and I see:

```
  error: jenkins.basicAuthUser: must be of type String
  jenkins.basicAuthPassword: must be of type String
```

Let me know, I'll be happy to PR this!

**Comment by plouc** [comment]
Hi @tomav, fine, thx, I now live in Japan. And you ?

You're right about the config, feel free to make a PR ;)

**Comment by tomav** [comment]
https://github.com/plouc/mozaik-ext-jenkins/pull/4

**Comment by MPV** [comment]
Maybe the same fix should be done in the `mozaik-demo` too?
https://github.com/plouc/mozaik-demo/blob/master/config.js#L27-L30
