### ISSUE TITLE
is 1.2.0 of this plugin compatible with mozaik-v2 ?

### ISSUE THREAD

**Issue by imranansari** [plouc/mozaik-ext-jenkins#24]

**Comment by plouc** [comment]
@imranansari, unfortunately, I haven't started the migration of this plugin to Mozaik V2, most of the projects I'm working on have moved to GitLab and use GitLab CI, It will probably be one day but it heavily depends on the time I have for it :/.

You can find extensions compatibility on this page http://mozaik.rocks/extensions/ and the progress here https://github.com/plouc/mozaik/issues/98.
