### ISSUE TITLE
Uncaught Error: No component defined for type "jenkins.jobs"

### ISSUE THREAD

**Issue by tomav** [plouc/mozaik-ext-jenkins#3]
Added extention using `npm i mozaik-ext-jenkins --save` and module if physically installed.

In `app.js`, added `mozaik.bus.registerApi('jenkins', require('mozaik-ext-jenkins/client'));`
I can see `info: registered API "jenkins"` when starting server.

But nothing appears, and I can see this message in my browser console:
`Uncaught Error: No component defined for type "jenkins.jobs"`

Tried with other widget and same problem.

Am I missing something?

Thank you @plouc

**Comment by plouc** [comment]
Mozaïk has 2 _parts_, the **server** which fetch the data, and the **frontend** which is made of react components, you also have to register the components on the **frontend** side:

``` javascript
// src/App.jsx
// ...
import jenkinsComponents from 'mozaik-ext-jenkins';

// ...

Mozaik.Registry.addExtensions({
    // ...
    jenkins: jenkinsComponents
});

// ...
```

let me know if it works

**Comment by plouc** [comment]
you can see the demo config [here](https://github.com/plouc/mozaik-demo/blob/master/src/App.jsx)

**Comment by tomav** [comment]
That was exactly the missing part. Thank you.

**Comment by plouc** [comment]
You're welcome :)
