### ISSUE TITLE
jenkins.view not working

### ISSUE THREAD

**Issue by benediktvaldez** [plouc/mozaik-ext-jenkins#7]
`module.exports.jobBuild` in ./src/client.js [line 65](https://github.com/plouc/mozaik-ext-jenkins/blob/master/src/client.js#L65) is `undefined`

When I tried moving `jobBuild` outside of the returned object it worked.

Not sure how you wanna address this @plouc, related issue is that `jobs` returns literally all jobs, not only for the requested view (this might be jenkins' fault though, not sure)

**Comment by plouc** [comment]
@benediktvaldez, using `module.exports` to address `jobBuild` was a bad idea, I'll change that.
For jenkins returning all jobs (or Mozaïk fetching all :)), I'll have to check.

**Comment by benediktvaldez** [comment]
@plouc Thanks :)

Another thing that would be cool, if I could simply ask for a pipeline, and list all of its stages and their status

**Comment by plouc** [comment]
Yes, I wanted to craft a widget for it, but unfortunately, last time I checked (don't remember when), I saw that the plugin didn't provided an API.

**Comment by benediktvaldez** [comment]
Ah, I see. At least I'm seeing it now, running Jenkins 1.644, I get a `pipelines` array with my response :+1:

**Comment by plouc** [comment]
@benediktvaldez, just checked for the view widget and jenkins only returns the view's jobs, so Mozaïk just display those jobs (tested with jenkins 1.618).

**Comment by plouc** [comment]
@benediktvaldez, any update on this ?

**Comment by benediktvaldez** [comment]
On closer inspection I think the problem is that my view is a display of pipelines rather than a list of jobs. When I try to use a view with the regular list of jobs everything works fine.

So, problem is on my side :+1: I'll look into extending this extension with support for pipelines.

Thanks!

![](http://drop.bdvs.info/1kfgs/4T3S6BBW+)
